<footer>
    <!--Horizontal Line that separtes the information above with the information below.-->
    <hr>
        <?php include 'nav.inc'; ?>
                <!--Div, devides the paragraph so i can put the information on the same line but aligning it to either the left or the right.-->
            <br>
            <!--A Hyperlink to an external website.-->
            <div class="jira_link_footer">
                <a class="footer_links" href= "https://thebestbigbraingroup.atlassian.net/jira/software/projects/SCRUM/summary"
                target="_blank"
                title="Go to The Best Big Brain Group Jira"
                hreflang="en">Go To The Company's Jira</a>
            </div>
            <!--A Hyperlink to send me the company an email.-->
            <div class="company_email">
            Email:
            <a class="footer_links" href="mailto:thebestbigbraingroup@gmail.com">info@thebestbigbraingroup.com.au</a></div>
            <!--Hyperlink to the website's github-->
            <div class="github_link_footer">
                Github:
                <a class="footer_links" href="https://github.com/moniquev45/project2.git" target="_blank">This website's github repository</a>
            </div>
            <!--Forces there to be a line break below to not squish all the the hyperlinks to the border of the page.-->
            <p class="copyright_in_footer">
            &copy; <strong>
                2025 The Best Big Brain Group. All Rights Reserved.
                </strong>
             </p>
            <hr>
</footer>