<footer>
            <!--Horizontal Line that separtes the information above with the information below.-->
            <hr>
            <ul>
                <li><a href="index.html">  Home  </a></li>
                <li><a href="jobs.html">  Jobs Listings  </a></li>
                <li><a href="apply.html">  Job Application  </a></li>
                <li><a href="contact.html"> Contact </a></li>
                <li><a href="about.html">  About Us  </a></li>
            </ul>
            <!--Div, devides the paragraph so i can put the information on the same line but aligning it to either the left or the right.-->
            <br>
            <!--A Hyperlink to an external website.-->
            <div class="Jira_Link_Footer">
                <a class="Footer_Links" href= "https://thebestbigbraingroup.atlassian.net/jira/software/projects/SCRUM/summary"
                target="_blank"
                title="Go to The Best Big Brain Group Jira"
                hreflang="en">Go To The Company's Jira</a>
            </div>
            <!--A Hyperlink to send me the company an email.-->
            <div class="Company_Email">
            Email:
            <a class="Footer_Links" href="mailto:thebestbigbraingroup@gmail.com">info@thebestbigbraingroup.com.au</a></div>
            <!--Hyperlink to the website's github-->
            <div class="Github_Link_Footer">
                Github:
                <a class="Footer_Links" href="https://github.com/moniquev45/Group_Project" target="_blank">This website's github repository</a>
            </div>
            <!--Forces there to be a line break below to not squish all the the hyperlinks to the border of the page.-->
            <p class="Copyright_in_footer">
            &copy; <strong>
                2025 The Best Big Brain Group. All Rights Reserved.
                </strong>
             </p>
            <hr>
</footer>