<header>
            <div class="Job_Position_And_Logo">
                <figure>
                <!--Change to company Logo-->  
                <a href="index.php"><img src="images/Pear_Company_Logo.png" alt="Pear Company Logo" class="Company_Logo"></a>
                <!-- Logo Link: https://www.shutterstock.com/image-vector/green-pear-vector-icon-logo-design-2308212369 -->
                </figure>
                <h1 class="Company_Name">The Best Big Brain Group </h1>
            </div>
            <nav>
                <ul>
                    <li><a href="index.php">  Home  </a></li>
                    <li><a href="jobs.php">  Jobs Listings  </a></li>
                    <li><a href="apply.php">  Job Application  </a></li>
                    <li><a href="contact.php"> Contact </a></li>
                    <li><a href="about.php"> About Us </a></li>
                </ul>
            </nav>
            <hr>
</header>